### ISSUE TITLE
[LLVM 6] Static evaluation of floating-point expressions causes some benchmarks to erroneously fail

### ISSUE THREAD

**Issue by keram88** [smackers/smack#476] opened 2019-07-29 05:28 UTC
Several SVCOMP benchmarks are failing with the upgrade to LLVM 6. The affected benchmarks include `floats-esbmc-regression/rint_true-unreach-call.i` in the `ReachSafety-Floats-develop-eb4150c-d820.ReachSafety-Floats` category. These benchmarks appear to be failing due to Clang/LLVM evaluating floating point expressions at compile time. This seems to be due to an optimization pass acquiring the ability to optimized such expressions versus previous LLVM versions.

Preliminary investigations have found the following:
* Clang is able to to reduce `rint_true-unreach-call.i` to `__VERIFIER_error` due to evaluating constant expressions under the round-to-nearest rounding mode, despite this program changing rounding modes.
* Clang and GCC outside of SMACK are both able to reduce this benchmark to a call to `__VERIFIER_error`.
* SMACK when run outside of SVCOMP mode does not appear to exhibit this behavior.
* GCC has a flag `-frounding-math` which inhibits this optimization, but the flag is not currently available in Clang.

**Comment by shaobo-he** [comment] 2020-04-13 21:07
I cannot reproduce it on chimera but it still manifests on emulab machines. I doubt if it's related to hardware.

**Comment by shaobo-he** [comment] 2020-12-23 09:09
Closed this issue as it's too old and hard to reproduce.

**Closed by shaobo-he** 2020-12-23 09:09 UTC
Labels: bug
