### ISSUE TITLE
Corral backend is extremely slow, comparing with Boogie

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#425] opened 2019-03-22 22:47 UTC
Hello,

I am writing to report an observation, regarding the performance of `Corral` and `Boogie`. So basically when using these two different backend to model check a LLVM IR code, the `Boogie` case performs quite well:

<img width="1369" alt="Screen Shot 2019-03-22 at 11 45 55 PM" src="https://user-images.githubusercontent.com/44623557/54856821-a9750980-4cfc-11e9-9eac-a36b1d344119.png">

However, `Corral` is just too slow. 

<img width="1161" alt="Screen Shot 2019-03-22 at 11 45 22 PM" src="https://user-images.githubusercontent.com/44623557/54856810-9bbf8400-4cfc-11e9-8035-7b5241fbe486.png">

It seems to me that somehow `Corral` does not effectively handle recursive calls. But besides that, could anyone give some tips to tune the `Corral` case, considering the potential optimization space by running `Boogie`.

**Comment by michael-emmi** [comment] 2019-03-23 01:14
Hi @ireneGP, the first thing I would try is enabling verbose output (`-v`) to see what Corral is doing:
```bash
$ smack -v --unroll=5 ./test4.ll
```
One potential issue is that that Corral starts with a coarse abstraction that only tracks a small subset of program variables, and keeps adding more tracked variables as infeasible (abstract) counterexamples are discovered. You can see this happening when you enable verbose output:
```
Single threaded program detected
LB: Took 0.29 s
Verifying program while tracking: {assertsPassed}
Program has a potential bug: False bug
Verifying program while tracking: {assertsPassed, $M.9}
Program has a potential bug: False bug
Verifying program while tracking: {assertsPassed, $M.9, $M.0, $M.8}
Program has a potential bug: False bug
Verifying program while tracking: {assertsPassed, $M.9, $M.0, $M.8, $M.1, $M.6}
Program has a potential bug: False bug
Verifying program while tracking: {assertsPassed, $M.9, $M.0, $M.8, $M.1, $M.6, $M.14}
<many more of the same>
```
It is possible to avoid this counterexample-guided abstraction refinement (CEGAR) by instructing Corral to track all variables initially with its `/trackAllVars` switch:
```bash
$ smack -v --unroll=5 --verifier-options "/trackAllVars" ./test4.ll 
```
Now Corral’s initial output should look more like this:
```
Single threaded program detected
LB: Took 0.30 s
Verifying program while tracking: {assertsPassed, $M.0, $M.1, $M.2, $M.3, $M.4, $M.5, $M.6, $M.7, $M.8, $M.9, $M.10, $M.11, $M.12, $M.13, $M.14, $M.15, $M.16, $M.17, $M.18, $M.19, $M.20, $M.21, $M.22}
```
Obviously this will vary depending on the input program.

While this is not the only possible thing that might be holding up Corral, this is the first thing I would try.

**Comment by ireneGP** [comment] 2019-03-23 08:28
@michael-emmi  Thank you so much michael! Here is the output:

<img width="1437" alt="Screen Shot 2019-03-23 at 9 28 29 AM" src="https://user-images.githubusercontent.com/44623557/54863848-106ede80-4d4e-11e9-9540-3ecbafd96710.png">

**Comment by ireneGP** [comment] 2019-03-23 08:32
@michael-emmi  Yes, when I use the option you mentioned, it becomes comparable to `Boogie`:

<img width="1440" alt="Screen Shot 2019-03-23 at 9 31 03 AM" src="https://user-images.githubusercontent.com/44623557/54863874-8410eb80-4d4e-11e9-9921-37cd9dad755d.png">


And:

<img width="1433" alt="Screen Shot 2019-03-23 at 9 32 32 AM" src="https://user-images.githubusercontent.com/44623557/54863884-9d199c80-4d4e-11e9-8c4f-85ce2c563d72.png">


Does this look normal to you?

**Comment by ireneGP** [comment] 2019-03-23 09:13
@michael-emmi  Yes, I tried some other cases and also encountered such msg:

````
Prover error: line 19 column 32: invalid parameter, unknown module `fixedpoint`
````

**Comment by michael-emmi** [comment] 2019-03-23 13:50
That is odd. It’s clear from Z3’s documentation that there was at some point a fixed point module. The examples [here](https://rise4fun.com/Z3/tutorial/fixedpoints) still refer to it like so
```
(set-option :fixedpoint.engine datalog)
```
but invoking Z3 on those examples gives the same error as you’re seeing. Although I have tried, I am not able to track down the Boogie/Corral code responsible for generating this line. However, I was able to find a Boogie commit from November (boogie-org/boogie@2dfbf64) that claims that Z3’s `fixedpoint` module is obsolete since version 4.8 — though I still cannot find a commit diff which removes such the generation of the line above.

I guess the thing to try now would be updating to more recent versions of Corral and Boogie.

**Comment by zvonimir** [comment] 2019-03-26 14:21
@ireneGP : I am having trouble reproducing your error on my machine. Which version of Z3 are you using?

**Comment by michael-emmi** [comment] 2019-03-26 14:24
Hey @zvonimir are you able to reproduce this error when running Z3 on the examples [here](https://rise4fun.com/Z3/tutorial/fixedpoints)?

**Comment by zvonimir** [comment] 2019-03-26 14:28
Nope. I am running Z3 4.8.1 and it is working on these examples. Moreover, when I look at SMT queries generated by Corral, there is nothing about `fixedpoint` module in them. I cannot figure out when Corral adds `fixedpoint` into its queries.

**Comment by michael-emmi** [comment] 2019-03-26 14:30
This is what I see:
```
$ z3 -version && cat test.smt2 && z3 test.smt2 
Z3 version 4.8.1 - 64 bit
(declare-rel a ())
(declare-rel b ())
(declare-rel c ())
(rule (=> b a))
(rule (=> c b))

(set-option :fixedpoint.engine datalog)
(query a)

(rule c)
(query a
 :print-answer true)
 (error "line 7 column 31: invalid parameter, unknown module 'fixedpoint'")
unsat
sat
true
```

**Comment by michael-emmi** [comment] 2019-03-26 14:30
Also, as noted above, I was also not able to track down where Boogie/Corral has ever inserted the `fixedpoint.engine` option.

**Comment by zvonimir** [comment] 2019-03-26 14:41
This is my output for the same command:
```
$ z3 -version && cat test.smt2 && z3 test.smt2
Z3 version 4.8.1 - 64 bit - build hashcode 016872a5e0f6
(declare-rel a ())
(declare-rel b ())
(declare-rel c ())
(rule (=> b a))
(rule (=> c b))

(set-option :fixedpoint.engine datalog)
(query a)

(rule c)
(query a
 :print-answer true)

unsat
sat
true
```

Weird. Maybe a discrepancy between what got packaged in Z3 releases for different platforms. Not sure.

**Comment by michael-emmi** [comment] 2019-03-26 14:41
@zvonimir do you have different output on the following command?
```
$ z3 -p | grep fixedpoint
[module] fp, description: fixedpoint parameters
    print_fixedpoint_extensions (bool) (default: true)
```

**Comment by zvonimir** [comment] 2019-03-26 14:44
```
$ z3 -p | grep fixedpoint
[module] fixedpoint, description: fixedpoint parameters
    print_fixedpoint_extensions (bool) (default: true)
[module] fp, description: fixedpoint parameters
    print_fixedpoint_extensions (bool) (default: true)
```
Hmmm, maybe they just renamed the module as `fp`.

**Comment by michael-emmi** [comment] 2019-03-26 14:50
Ah hah: Z3Prover/z3@9109968

**Comment by michael-emmi** [comment] 2019-03-26 14:57
Anyhow: seems like Z3 is no longer accepting `fixedpoint`, and we cannot figure where Boogie/Corral is actually generating this line. Maybe we should push this to Akash?

@ireneGP I think you can safely ignore this error as a spurious warning for now.

**Comment by zvonimir** [comment] 2019-03-26 16:21
@ireneGP : Something weird is happening here and we are having trouble tracking down this problem. It would great if you could help us out a little bit to get to the bottom of this. It seems that fixedpoint module is used only when Duality is selected as a backend solver, which should not happen (unless you altered that behavior).

Could you maybe run SMACK with `--debug` option? Lots of debug info will be printed on the screen and you can disregard most of it. The main thing I am looking for is the line towards the end of the log that says exactly how Corral got invoked and using which command like options. Please copy-paste this line here.

Finally, could you also provide us with the exact git commit hash of your Corral build? Just to make sure we are all using the same version of Corral. Thanks!

**Comment by ireneGP** [comment] 2019-03-26 16:46
@zvonimir  Sure thing. I have those logs with `--debug` enabled. But that's just too large. Here it is.

[log.txt](https://github.com/smackers/smack/files/3009218/log.txt)


I am using this `Corral` : d7d389f22d4679430e44d4c0c9c878957129f4ed. exactly the same version required by default.

**Comment by zvonimir** [comment] 2019-03-26 20:16
I still cannot reproduce it. Any chance you could attach your bpl file as well? Thx!

**Comment by ireneGP** [comment] 2019-03-27 10:38
@zvonimir Sure, will do later today. Thanks a lo!

**Comment by zvonimir** [comment] 2019-11-04 17:24
Closing this for now since we have no way or reproducing it.

**Closed by zvonimir** 2019-11-04 17:24 UTC
