### ISSUE TITLE
Include NaN in floating point modelling

### ISSUE THREAD

**Issue by delcypher** [smackers/smack#66] opened 2015-02-08 13:12 UTC
I've noticed that two SV-COMP benchmarks were translated imprecisely by SMACK leading to a bug in the original C program disappearing. (note I'm looking at the `bpl` generated in the [sbb repo](https://github.com/smackers/sbb/blob/a33974e09e389da6281dd423d9fe4996fd20537d/sv-comp/float-benchs/nan_float_false-unreach-call.c_.bpl))

The benchmarks are
- `sv-comp/float-benchs/nan_float_false-unreach-call.c_.bpl`
- `sv-comp/float-benchs/nan_float_false-unreach-call.c_.bpl`

I think I've condensed the issue down to this program

```
type float;
axiom (forall f1, f2: float :: f1 != f2 || $foeq(f1,f2));
function $foeq(f1:float, f2:float) : bool;
procedure main()
{
    var x:float; // unconstrained value
    assert $foeq(x,x);
}
```

In this program the assertion cannot fail because we are comparing the
same variable against itself so "f1 != f2" is false in the axiom.

However I suspect in the original C program this could actually fail
because the float could be NaN which is incomparable (even with
itself). So I think you need to introduce the $isnan() function in the
Boogie programs SMACK generates so you could do something like this

```
type float;
axiom (forall f1, f2: float :: f1 != f2 || $isnan(f1) || $isnan(f2) ||
$foeq(f1,f2));
function $foeq(f1:float, f2:float) : bool;
function $isnan(f1:float) : bool;
procedure main()
{
    var x:float; // unconstrained value
    assert $foeq(x,x);
}
```

Now the above program definitely has a bug which is what we want. If
SMACK knows that a particular float is not NaN it could
insert `assume !$isnan(x)` in the relevant places or it could use `where` on the
variable declaration if you know it will always not be NaN (even if it
gets havoced later) like this

```
type float;
axiom (forall f1, f2: float :: f1 != f2 || $isnan(f1) || $isnan(f2) ||
$foeq(f1,f2));
function $foeq(f1:float, f2:float) : bool;
function $isnan(f1:float) : bool;
procedure main()
{
    var x:float where !$isnan(x);
    assert $foeq(x,x);
}
```

**Comment by michael-emmi** [comment] 2015-02-09 11:46
Thanks for pointing this out, Dan!

**Comment by zvonimir** [comment] 2019-01-23 13:00
@liammachado : Is this still a problem?

**Comment by zvonimir** [comment] 2019-07-16 03:46
@liammachado : Is this still a problem?

**Comment by shaobo-he** [comment] 2020-02-04 22:29
@zvonimir This is not an issue when the `--float` flag is enabled. Can I close it?

**Comment by zvonimir** [comment] 2020-02-04 23:36
Hmmm, this is interesting. This means that without `--float` we are not even sound in certain situations, which is not good.
We should fix this by making `$foeq` be an uninterpreted function, meaning we should not try to interpret it as an equality.

**Comment by shaobo-he** [comment] 2020-02-05 05:55
> Hmmm, this is interesting. This means that without `--float` we are not even sound in certain situations, which is not good.
> We should fix this by making `$foeq` be an uninterpreted function, meaning we should not try to interpret it as an equality.

I just realized that we don't have the axioms constraining `$foeq` anymore. It's an uninterpreted function. So we're good.

**Comment by shaobo-he** [comment] 2020-02-05 05:58
Closed this issue because it's not reproducible for SMACK version 5b478dd0838100c5216a2155a24d95c9e06ba68c.

**Closed by shaobo-he** 2020-02-05 05:58 UTC
Labels: bug

**Comment by zvonimir** [comment] 2020-02-05 16:35
Do we have a regression for this (something with an equality like this)?

**Comment by shaobo-he** [comment] 2020-02-06 19:23
> Do we have a regression for this (something with an equality like this)?

No, we don't. Should I get one?

**Comment by zvonimir** [comment] 2020-02-24 22:38
Yes, please add a regression.
