### ISSUE TITLE
Inconsistent naming for Boogie uninterpreted floating point conversions

### ISSUE THREAD

**Issue by keram88** [smackers/smack#329] opened 2018-06-19 03:59 UTC
Currently, when floating point is turned off in SMACK, all floating point types are converted to `float` by Naming.cpp. This leads to the need to declare conversion operators such as
``` boogie
function $bitcast.float.i64(i: i64) returns (float);
```
We could have a `ufloat` type or another similarly named type to indicate the function operates on an uninterpreted floating type. However, adding this to smack.c would require duplicating the "uninterpreted" function declarations as they are also used when floating point is turned on.

**Comment by keram88** [comment] 2018-06-20 07:40
Yes. When I changed these declarations to type `ufloat` our floating point regressions failed because these declarations are also used when floating point is enabled. I reported this more as a reminder for cleaning up smack.c when addressing issue #308.

**Comment by shaobo-he** [comment] 2020-04-13 21:16
Closed this because I cannot reproduce it using the latest version.

**Closed by shaobo-he** 2020-04-13 21:16 UTC
