### ISSUE TITLE
Some string constant should be initialized

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#179] opened 2016-07-01 18:05 UTC
Currently we don't initialize string constant as indicated by the following line of code https://github.com/smackers/smack/blob/master/lib/smack/CodifyStaticInits.cpp#L41

It works fine as long as the string content is used by the program. Consider the following program,

``` C
#include "smack.h"

void warning_or_die(char *x) {
  while(*x) {
    if (*x == 'D')
      exit(1);
    else if (*x == 'W')
      break;
    ++x;
  }
  printf("no big deal\n");
}

int main()
{
  char* x = "D: unsound";
  warning_or_die(x);
  assert(0);
}
```

SMACk will give a false positive.

**Comment by zvonimir** [comment] 2016-07-01 18:10
In general, SMACK is not very good when it comes to handling of strings. I have not seen great need for better support for strings so far. If this is a big issue for you, I suggest you try to do this update yourself and create a pull request for it.

**Comment by michael-emmi** [comment] 2016-07-02 13:04
I have also come across practical examples that need some simple string reasoning, e.g., in security-critical code.

I believe that string reasoning does not work simply because we remove string-type static initializers in the translation. It is easy to add them back. However, once you do you will notice a scalability problem because of the huge number of strings added by the Boogie code declarations from `smack.h`.

I think a good fix for this would have to include the static initializers for (at least some) program strings, while not including the initializers for strings arising from Boogie code declarations.

**Comment by zvonimir** [comment] 2016-07-02 18:37
@Guoanshisb made a similar suggestion yesterday saying that we should do a light-weigh analysis that would ignore all (constant) strings flowing into printf, fprintf, __SMACK_code, etc.
Maybe this would be worth implementing.

**Comment by zvonimir** [comment] 2016-12-19 15:54
This has been implemented, right?
@Guoanshisb : could you create a regression for this?

**Comment by michael-emmi** [comment] 2016-12-19 18:05
There are already regressions for this, e.g.,
````
$ cat test/basic/strings.c 
#include <smack.h>

// @expect verified

const char *s1 = "abcdefg";
const char *s2 = "tuvwxyz";

int main() {
  assert(s1[3] == 'd');
  return 0;
}
````

**Comment by zvonimir** [comment] 2016-12-19 18:09
Great, then I think we can close this. Yes?

**Comment by zvonimir** [comment] 2017-10-27 02:53
This has been implemented and taken care of.

**Closed by zvonimir** 2017-10-27 02:53 UTC
Labels: enhancement
