### ISSUE TITLE
examples/simple/simple.c fails verification with --verifier=boogie

### ISSUE THREAD

**Issue by epdtry** [smackers/smack#145] opened 2015-12-04 23:29 UTC
On the current `develop` branch, running `smack --verifier=boogie examples/simple/simple.c` incorrectly reports an error on line 11.

`git bisect` identifies revision 6150195 ("Unbounded verification is the default"), which changed the default for `smack`'s `--unroll` option from 2 to None.  Adding `--unroll=2` to the `smack` command line results in no errors.

**Comment by zvonimir** [comment] 2015-12-05 23:36
Thanks for reporting this issue. We should clarify this better in our documentation (or change this default behavior), but this is in fact currently expected behavior of SMACK. Our design decision was that when no unrolling/inlining bound is selected, we stick with the default behavior of the backend verifier.
In the case of Boogie, that means that procedures are not being inlined, which in turn means that Boogie attempts to perform modular verification procedure by procedure. Since in this case there are no pre- or post-conditions on `incr`, it fails to prove the assertion in `main`.
Given that this is clearly causing confusion, we might alter the meaning of our command line options, and maybe create an additional command line switch.

**Comment by zvonimir** [comment] 2016-04-04 02:03
To avoid similar confusions in the future, this issue has been addressed by changing the default behavior of SMACK when using Boogie. Now SMACK always sets unroll bound to 1 for all backend verifiers (which support that options).

**Closed by zvonimir** 2016-04-04 02:03 UTC
