### ISSUE TITLE
Compiling standard makefile projects to boogie with smack

### ISSUE THREAD

**Issue by nimrodpar** [smackers/smack#202] opened 2017-01-10 15:02 UTC
Great work with this project guys! I'm trying to use smack to compile some standard projects (like `wget`, `coreutils`, `openssl`) to boogie, but i can't find any info on this. There's `https://github.com/smackers/smack/blob/master/examples/simple-project/Makefile` but that seems to only get you to the point where llvm bitcode is created.

Cheers.

**Comment by zvonimir** [comment] 2017-01-10 15:05
Yeah, we should write a little tutorial on this topic. We have really good experience with the whole-program-llvm project: https://github.com/travitch/whole-program-llvm
You can use whole-program-llvm to generate a bc file in which all of your files are compiled and linked into. Then you can run SMACK on this bc file.
@Guoanshisb can provide you with more support since he has more experience with this process than I do.

**Comment by Guoanshisb** [comment] 2017-01-11 00:37
Hi @nimrodpar, thanks for your interest in SMACK. Yes, you can compile a lot of make-based projects to Boogie with the help of whole-program-llvm. I will use `wget` as an example to show how to do it.

Install whole-program-llvm, download `wget-1.18`, and enter `wget-1.18` folder,
```
$ export LLVM_COMPILER=clang
$ export CC=wllvm
$ export CXX=wllvm++
$ export CFLAGS="-g -O0" # note these two flags are very important to SMACK.\
But sometimes exporting CFLAGS doesn't work. So you may have to modify makefile directly.
$ ./configure
$ make
$ cd src
$ extract-bc wget
$ smack wget.bc -bpl wget.bpl -t -q
```
 `wget.bpl` is the Boogie program of `wget`.
I hope it helps. Please let me know if you can reproduce it.

**Comment by nimrodpar** [comment] 2017-01-11 13:21
Yeah, that does the trick, thanks!

p.s. i think that even just adding this small snippet to the readme would be good.

**Comment by shaobo-he** [comment] 2020-02-04 22:01
Closed this issue as it has been resolved and is a duplicate of #407

**Closed by shaobo-he** 2020-02-04 22:01 UTC

**Comment by zvonimir** [comment] 2020-02-04 23:40
How was this issue resolved?

**Comment by shaobo-he** [comment] 2020-02-05 00:25
I answered this question and would like to have the discussion about adding documents to a more recent issue (i.e., #407).
