### ISSUE TITLE
about --integer-overflow

### ISSUE THREAD

**Issue by zhanye** [smackers/smack#457] opened 2019-06-06 07:09 UTC
[root@ecos2.7.4 /data/xz]#smack test.c --integer-overflow
SMACK program verifier version 1.9.3
#0 0x0000000001ac1e75 (llvm2bpl+0x1ac1e75)
#1 0x0000000001ac006e (llvm2bpl+0x1ac006e)
#2 0x0000000001ac01aa (llvm2bpl+0x1ac01aa)
#3 0x00007f72135476d0 __restore_rt (/lib64/libpthread.so.0+0xf6d0)
#4 0x0000000000c5d345 (llvm2bpl+0xc5d345)
#5 0x00000000019e57fb (llvm2bpl+0x19e57fb)
#6 0x00000000006e0abd (llvm2bpl+0x6e0abd)
#7 0x00000000006e2711 (llvm2bpl+0x6e2711)
#8 0x0000000001a06360 (llvm2bpl+0x1a06360)
#9 0x00000000006b5f33 (llvm2bpl+0x6b5f33)
#10 0x00007f721296e445 __libc_start_main (/lib64/libc.so.6+0x22445)
#11 0x00000000006b4f80 (llvm2bpl+0x6b4f80)
Stack dump:
0.      Program arguments: llvm2bpl /data/xz/b-ZfRIXo.bc -bpl /data/xz/a-WQTUN9.bpl -warnings -source-loc-syms -entry-points main -mem-mod-impls -integer-overflow
Running pass 'Checked integer arithmetic intrinsics' on module '/data/xz/b-ZfRIXo.bc'.
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 615, in main
    frontend(args)
  File "/usr/local/bin/../share/smack/top.py", line 320, in frontend
    return link_bc_files(bitcodes,libs,args)
  File "/usr/local/bin/../share/smack/frontend.py", line 314, in link_bc_files
    llvm_to_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 344, in llvm_to_bpl
    try_command(cmd, console=True)
  File "/usr/local/bin/../share/smack/utils.py", line 67, in try_command
    raise Exception("segmentation fault")
Exception: segmentation fault

This is my code:
      1 #include "smack.h"
      2
      3 int func(x)
      4 {
      5     return x+1;
      6 }
      7
      8 int main()
      9 {
     10     int a = __VERIFIER_nondet_int();
     11     int b = func(a);
     12     __VERIFIER_assert(b > a);
     13     return 0;
     14 }

When I use smack to check  ingeter over, it occurred an segmentation fault.
who knows why? Thank you.

**Comment by keram88** [comment] 2019-06-06 07:36
Hello,
I was unable to reproduce this on the `develop` and `master` branches, so the cause isn't immediately obvious.
Which branch of SMACK are you using? And how did you build SMACK?

**Comment by zhanye** [comment] 2019-06-06 08:16
@keram88 , I do not build SMACK at all, I just get the SMACK environment from my partner.
But I'm sure that our SMACK can work. If I use "smack test.c" or "smack test.c --unroll 100" or "smack test.c --memory-safety", all of these can get an answer. Only the parameter "--integer-overflow" will be wrong.
by the way, my SMACK version is 1.9.3, is it the latest? need update?

**Comment by zvonimir** [comment] 2019-06-06 10:38
Thanks for reporting your problem @zhanye.
The same as @keram88, I cannot reproduce it on my machine either, and so it would be really hard for us to debug this. The release you have is our latest release, but we will push out another release very soon, in the next week or so. So then you should update your SMACK installation and try this again. I will let you know here once we make the next release.

**Comment by zhanye** [comment] 2019-06-10 06:20
OK, thanks, I will try your new version later.
There are always some strange problems in machine's world.

**Comment by shaobo-he** [comment] 2020-02-04 21:23
Closed this issue because of irreproducibility. @zhanye feel free to reopen this issue if you are able to reproduce it on the current develop branch.

**Closed by shaobo-he** 2020-02-04 21:23 UTC
