### ISSUE TITLE
Buggy behavior when handling global array

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#423] opened 2019-03-21 10:08 UTC
Hello,

I am reporting the following observation. Given the following code:

````
nclude "smack.h"

int access[100] = {0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0
                };

void check_r(unsigned long long i) {
        assert(access[i] == 0);
}

void main()
{
        check_r(0);
}
````

The output seems normal:

````
➜  ubuntu1604 time smack --unroll=10 --verifier=boogie ./rec.c

SMACK program verifier version 1.9.3
./rec.c:19:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main()
^
./rec.c:19:1: note: change return type to 'int'
void main()
^~~~
int
1 warning generated.
SMACK found no errors with unroll bound 10.
smack --unroll=10 --verifier=boogie ./rec.c  1.19s user 0.24s system 100% cpu 1.432 total

````

However, by changing the size of the global array (from 100 to 110):

````
#include "smack.h"

int access[110] = {0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0,
                  0,0,0,0,0,0,0,0,0,0
                };

void check_r(unsigned long long i) {
        assert(access[i] == 0);
}

void main()
{
        check_r(0);
}
````

I got some spurious outputs as the follows:

````
➜  ubuntu1604 time smack --unroll=10 --verifier=boogie ./rec.c

SMACK program verifier version 1.9.3
./rec.c:20:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main()
^
./rec.c:20:1: note: change return type to 'int'
void main()
^~~~
int
1 warning generated.
/usr/local/share/smack/lib/smack.c(44,1): This assertion might not hold.
Execution trace:
    ./rec.c(22,2):
    /usr/local/share/smack/lib/smack.c(1452,3):
    ./rec.c(22,2):
    ./rec.c(17,2):
    /usr/local/share/smack/lib/smack.c(257,3):

SMACK found an error.
smack --unroll=10 --verifier=boogie ./rec.c  1.24s user 0.21s system 103% cpu 1.406 total

````

Does this seem like a bug or something?

**Comment by michael-emmi** [comment] 2019-03-23 01:34
This is a duplicate of #367

**Comment by zvonimir** [comment] 2019-03-27 15:10
@ireneGP : As you can see from the duplicate issue, Boogie sometimes has completeness issues in the presence of large arrays. In this case using Corral improves completeness since Corral relies on the theory of arrays. So that should resolve your issue. I will hence close this for now, and please do reopen it if you are still stuck.

**Closed by zvonimir** 2019-03-27 15:10 UTC
Labels: duplicate
