### ISSUE TITLE
Reimplementing memory safety checking

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#197] opened 2016-12-19 15:59 UTC
Memory safety checking should be implemented as a transformation over Boogie ASTs after all. The problem with the current implementation, which introduces calls to memory safety checking function in LLVM IR, is that it typically causes for DSA to merge everything into one region (since this same function is called everywhere with different pointers). I think that the solution would be to reimplement memory safety checking as a pass over the generate Boogie ASTs. This pass would inject calls to our memory safety checking function directly in Boogie, thereby not causing problems with DSA.

**Comment by zvonimir** [comment] 2016-12-19 15:59
@michael-emmi : I would appreciate your feedback/thoughts.

**Comment by michael-emmi** [comment] 2016-12-19 17:53
Well I think that it is always better to implement things at the LLVM level, so long as it is possible, and does not force a collapse of memory regions.

Before going 

````
````

**Comment by michael-emmi** [comment] 2016-12-19 18:00
Well I think that it is always better to implement on LLVM IR, as long as it is possible to do so, without forcing complete region collapse.

In this case, I think there may still be ways to convince DSA not to collapse regions. Consider the following example.
````
#include <smack.h>

int foo(int*) __attribute__((const));

void use(int);

int main(void) {
  
  int x = 0;
  int y = 1;
  
  use(foo(&x));
  use(foo(&y));
    
  return 0;
}
````
In this case the `const` attribute means that the `foo` function does not have any effects besides its return value; see http://nshipster.com/__attribute__/

If you run this through Smack you will see that the regions of `x` and `y` are not merged on account of calls to `foo`, unless you remove the `const` attribute. For this to work out, `foo` must return a value, and that value must be consumed, e.g., by the `use` function — LLVM would otherwise recognize calls to `foo` as superfluous.

Perhaps the same trick would work with the memory-safety checking procedure?

**Comment by zvonimir** [comment] 2016-12-19 18:21
I agree that sticking with LLVM IR is better when possible. So I guess let's see if it is doable in this case.
Take a look at this regression:
https://github.com/smackers/smack/blob/master/test/memory-safety/structure1.c
When you execute SMACK on this with `--memory-safety` enabled, it will report collapsing of arguments when the memory safety function check gets invoked. Adding the `const` attribute does not help in this case. In fact, I am not sure exactly why the collapse happens since we are only casting them into `i8*`. I think we should explore this further.

**Comment by michael-emmi** [comment] 2016-12-19 18:27
But there is only one region in this example even with memory safety turned off.

**Comment by zvonimir** [comment] 2016-12-19 18:34
Ah, I see, I guess that due to array accesses the memory region maps to `i8` type even without memory safety checking enabled. Ok, let me think more about this and try to generate a better small example.

**Comment by michael-emmi** [comment] 2016-12-19 18:38
Also, I think you have to have both (a) the const attribute and (b) no implementation of the function for LLVM to analyze. So to really test out that idea you would have to give a Boogie-only implementation of the memory safety test function.

**Comment by michael-emmi** [comment] 2016-12-19 18:39
… which also would require you to have the memory checking function return something, and to have some statement to consume its value, so that LLVM does not optimize away the calls.

**Comment by zvonimir** [comment] 2016-12-20 04:52
Here is a simple regression showing this problem:
```
int main(void) {
  int *x = (int*)malloc(sizeof(int));
  int *y = (int*)malloc(sizeof(int));
  *x = 10;
  *y = 20;
  free(x);
  free(y);
  return 0;
}
```
When run with `--memory-safety` the generated Boogie file contains just one memory map, while when run without this flag it contains two memory maps.

**Comment by michael-emmi** [comment] 2016-12-20 16:22
Just pushed a fix. It would be nice to see whether this improves the region splitting and overall runtime of the important benchmarks.

**Comment by michael-emmi** [comment] 2016-12-20 18:22
This does improve at least some benchmarks. The following goes from 1 region and 14 minutes to 5 regions and 7.5 minutes.
````
smack -x=svcomp --memory-safety basename_false-unreach-call_true-no-overflow_true-valid-memsafety.i --unroll 11 -t
````

**Comment by Guoanshisb** [comment] 2016-12-20 18:40
Thanks, Mike. I am testing your fixes on all memory safety categories and
will let you know how it goes.

Michael Emmi <notifications@github.com>于2016年12月20日周二 上午11:22写道：

**Comment by zvonimir** [comment] 2016-12-21 02:51
We actually do see several less timeouts with this fix, and so it would be good to keep it (thanks!). There is one issue though - it does not work with bitvectors, and there are memory safety benchmarks for which we need to enable bitvector reasoning. For example see the attached file with packed bitfields, which requires `--bit-precise` to be enabled.
[test-bitfields-1_true-valid-memsafety.zip](https://github.com/smackers/smack/files/665354/test-bitfields-1_true-valid-memsafety.zip)

**Comment by michael-emmi** [comment] 2016-12-22 19:52
Latest commit f6dbd4f fixes the memory-safety check, but there is still another problem with that example due to conflicting types for malloc.

**Comment by zvonimir** [comment] 2016-12-22 19:53
Thanks!
Did this branch introduce the conflicting malloc types?
This example works in the develop branch.

**Comment by michael-emmi** [comment] 2016-12-22 19:59
No, this branch does not touch malloc. Develop branch has the same problem for me. It must be an non-platform-independent thing. This is what I get:
````
$ smack -t ~/Downloads/test-bitfields-1_true-valid-memsafety.i --bit-precise --memory-safety -x=svcomp && grep malloc a.bpl
SMACK program verifier version 1.7.1
/Users/mje/Code/smack/test-bitfields-1_true-valid-memsafety-F2OpaE.i:7:36: warning: unknown attribute '__leaf__' ignored [-Wunknown-attributes]
     __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__nonnull__ (1, 2)));
                                   ^
/Users/mje/Code/smack/test-bitfields-1_true-valid-memsafety-F2OpaE.i:5:14: warning: incompatible redeclaration of library function 'memcpy' [-Wincompatible-library-redeclaration]
extern void *memcpy (void *__restrict __dest,
             ^
/Users/mje/Code/smack/test-bitfields-1_true-valid-memsafety-F2OpaE.i:5:14: note: 'memcpy' is a builtin with type 'void *(void *, const void *, unsigned long)'
/Users/mje/Code/smack/test-bitfields-1_true-valid-memsafety-F2OpaE.i:9:67: warning: unknown attribute '__leaf__' ignored [-Wunknown-attributes]
extern void *malloc (size_t __size) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__malloc__)) ;
                                                                  ^
/Users/mje/Code/smack/test-bitfields-1_true-valid-memsafety-F2OpaE.i:9:14: warning: incompatible redeclaration of library function 'malloc' [-Wincompatible-library-redeclaration]
extern void *malloc (size_t __size) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__malloc__)) ;
             ^
/Users/mje/Code/smack/test-bitfields-1_true-valid-memsafety-F2OpaE.i:9:14: note: 'malloc' is a builtin with type 'void *(unsigned long)'
/Users/mje/Code/smack/test-bitfields-1_true-valid-memsafety-F2OpaE.i:11:62: warning: unknown attribute '__leaf__' ignored [-Wunknown-attributes]
extern void free (void *__ptr) __attribute__ ((__nothrow__ , __leaf__));
                                                             ^
5 warnings generated.
warning: collapsing DSA node
unable to merge call-site arguments with parameters to function __SMACK_check_memory_safety
in function:
  main
in block:
  if.end
at instruction:
  %5 = bitcast i8* %b to i8*
at value:
  %5 = bitcast i8* %b to i8*
node:
  0: i8,  1: i8,  : HUMREP


SMACK generated a.bpl
  call $galloc(malloc, 8);
const malloc: ref;
axiom (malloc == $sub.ref(0, 30997));
procedure  malloc($i0: bv64)
  call $r := $malloc($bv2int.64($i0));
procedure  $malloc(n: ref) returns (p: ref)
  call $p0 := malloc(2bv32);
````
There you can see that malloc’s argument is 64-bit yet the call in main is 32bit.

**Comment by michael-emmi** [comment] 2016-12-22 20:03
Another issue common to malloc and the memory-safety check when bit-precision is turned on: we are converting bit-vector literals to integers, e.g., in `call $p0 := malloc(2bv32);`. This is pretty silly. We might be way more efficient if we recognized that certain literals were only going to be used as integers, and then avoid representing them as bit-vectors only to convert them back to integers.

**Comment by zvonimir** [comment] 2016-12-22 20:09
Ah, you have to compile this benchmark with `--clang-options=-m32`. It could be that the benchmark contains something that makes it incompatible for 64-bit platforms. Not sure. I guess we should explore this further.

**Comment by michael-emmi** [comment] 2016-12-22 20:12
Ok, good, that works.

**Comment by zvonimir** [comment] 2016-12-22 23:04
Ah, something is still not working properly. Please see the attached file.
[test-0137_false-valid-deref.zip](https://github.com/smackers/smack/files/670021/test-0137_false-valid-deref.zip)
This is the error we see:
```
/proj/SMACK/SMACKBenchResults/data/a-eGyh7B.bpl(1974,10): Error: use of undeclared function: $bitcast.i32.ref
```

**Comment by zvonimir** [comment] 2018-06-05 01:42
@michael-emmi : I've been plowing through our open issues, and this one is still outstanding. Could you maybe take a look at the last comment above?

**Comment by michael-emmi** [comment] 2018-06-05 02:00
will require some free time; possibly later this week.

**Comment by michael-emmi** [comment] 2018-06-06 03:17
Are you still able to reproduce this? I suspect the problem might have gone away, given all of the changes of the last two years :-) I haven’t tried yet on Linux, but on Mac with the latest develop commit I don’t have this problem:
````
smack -t -x=svcomp test-0137_false-valid-deref.i --bit-precise --memory-safety --clang-options=-m32 && boogie /noVerify /doModSetAnalysis a.bpl
SMACK program verifier version 1.9.0
...
<lots of noise from Clang and DSA>
...
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
SMACK generated a.bpl
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.

Boogie program verifier finished with 0 verified, 0 errors
````
I’ve also tried different variations of those flags. Not seeing a problem with generated Boogie code.

**Closed** 2018-10-05 08:52 UTC
Labels: refactoring
