### ISSUE TITLE
Exception in Boogie

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#421] opened 2019-03-20 12:50 UTC
Hello, 

I am using the `Boogie` backend verifier for some model checking tasks. And here is the output of one case:

````
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 618, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 487, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: [ERROR] FATAL UNHANDLED EXCEPTION: System.StackOverflowException: The requested operation caused a stack over
flow.
  at Microsoft.Boogie.LoopUnroll.Visit (Microsoft.Boogie.LoopUnroll+GraphNode node) [0x00007] in <ed84cc86da2b4ac8b8fa07
791cfc2b80>:0
  at Microsoft.Boogie.LoopUnroll.Visit (Microsoft.Boogie.LoopUnroll+GraphNode node) [0x0010e] in <ed84cc86da2b4ac8b8fa07
791cfc2b80>:0

````

Does this seems suspicious?

**Comment by michael-emmi** [comment] 2019-03-23 01:37
I suspect this might be a duplicate of #218; could you provide a (minimal) example?

**Comment by zvonimir** [comment] 2019-03-26 12:23
Yep, we've seen this exception before when large unroll bounds are used with Boogie. So I suspect this is what is happening. Could you let us know how you invoked SMACK when you got this exception?

**Comment by zvonimir** [comment] 2019-11-04 17:25
Closing this for now since we have no way or reproducing it.

**Closed by zvonimir** 2019-11-04 17:25 UTC
