### ISSUE TITLE
Adding ll files as regressions to SMACK

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#321] opened 2018-06-05 20:47 UTC
This came up several times in the past several months. As the usage scenarios of SMACK are expanding beyond just C/C++ programs, we are running into situations where we need regressions for LLVM IR programs that are not easy (or are even impossible) to generate from C/C++.
I think the right move would be to add ll files to our regression suite for such situations. SMACK already supports taking ll files as input, and it probably would not be hard to update `regtest.py` to support ll files.
The main drawback that I can see is that LLVM IR sometimes changes between LLVM versions, and so such regressions would have to be updated with LLVM versions sometimes.
Thoughts?

**Comment by michael-emmi** [comment] 2018-06-05 22:04
Why not just run the regression conditionally, with the frontend that generates the code, if that frontend is available — e.g., in the path — and otherwise ignore the regression? Is this too much trouble?

**Comment by zvonimir** [comment] 2018-06-05 22:09
As we are slowly moving towards multi-language verification, what you suggested would I guess make sense in the long run. I mean, we already have Rust regressions somewhere in @keram88 Rust branch.
How should we structure the regressions in that case? Should we have top-level folders indicating languages (c,cpp,ll,rust,etc.), and then subfolders within these with regression features? Or something else?

**Comment by michael-emmi** [comment] 2018-06-05 22:11
On the other hand, perhaps maintaining LLVM-code regression tests is not as bad as we think. After all, how does LLVM handle this? Surely they don’t have to rewrite hundreds/thousands of regression tests every time they add/update some language feature?

**Comment by michael-emmi** [comment] 2018-06-05 22:12
The filesystem organization that you propose sounds reasonable to me.

**Comment by keram88** [comment] 2019-06-19 16:59
I investigated this a bit ago and found their AutoUpgrade functionality, but wasn't sure about how committed they were to it based on some mailing list posts. 
However, I finally found what looks like LLVM's policy:
> IR Backwards Compatibility
> 
> When the IR format has to be changed, keep in mind that we try to maintain some backwards compatibility. The rules are intended as a balance between convenience for llvm users and not imposing a big burden on llvm developers:
> 
> - The textual format is not backwards compatible. We don’t change it too often, but there are no specific promises.
> - Additions and changes to the IR should be reflected in test/Bitcode/compatibility.ll.
> - The current LLVM version supports loading any bitcode since version 3.0.
> - After each X.Y release, compatibility.ll must be copied to compatibility-X.Y.ll. The corresponding bitcode file should be assembled using the X.Y build and committed as compatibility-X.Y.ll.bc.
> - Newer releases can ignore features from older releases, but they cannot miscompile them. For example, if nsw is ever replaced with something else, dropping it would be a valid way to upgrade the IR.
> -  Debug metadata is special in that it is currently dropped during upgrades.
> -  Non-debug metadata is defined to be safe to drop, so a valid way to upgrade it is to drop it. That is not very user friendly and a bit more effort is expected, but no promises are made.

https://llvm.org/docs/DeveloperPolicy.html#ir-backwards-compatibility

It appears we can use bc files for our tests, since they're saying LLVM should load bc files from LLVM 3.0. So maybe we can add bc tests (originally compiled from an ll file).
My understanding from a mailing post I can't currently find is that they will warn when something is being ignored. If that is the case, then we can disassemble the file and upgrade it. I know this doesn't sound ideal, but that should only be an issue when LLVM gets upgraded. Maybe we can add some auxiliary file to document what the test is supposed to do.
I know this isn't ideal, so we should only use such tests for things that are near impossible to express any other way.

**Comment by shaobo-he** [comment] 2020-10-07 06:36
It appears we don't really have a strong case for this issue. Source language frontends are sufficient to produce bc files for testing SMACK.

**Closed by shaobo-he** 2020-10-07 06:36 UTC
Labels: enhancement
