### ISSUE TITLE
Redundant steps in CI

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#708] opened 2021-03-17 07:45 UTC
Currently, our CI spawns a dozen of jobs, each of which builds SMACK and tests a folder. So the build step seems redundant. I think maybe a better idea is to build a Docker image first and run that image on each folder in parallel.

**Comment by zvonimir** [comment] 2021-03-17 16:21
I don't think this is a big problem. CI is pretty fast now that we switched to actions. I would not worry about this. Also, this adds a level of indirection into the CI process, which then makes it harder to debug it and root cause problems.

**Comment by zvonimir** [comment] 2021-04-02 22:33
I think this is not a high priority since our CI is pretty fast these days. Closing it.
@shaobo-he feel free to reopen it.

**Closed by zvonimir** 2021-04-02 22:33 UTC
