### ISSUE TITLE
Model memcmp

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#575] opened 2020-05-06 01:51 UTC
It turns out at least Rust uses `memcmp`.

**Comment by zvonimir** [comment] 2020-05-09 19:21
Could you attach bc file for this?
Also, I could not find memcmp in the LLVM language reference manual. Are you referring here to the memcmp C standard library function: https://en.cppreference.com/w/c/string/byte/memcmp
???
Or something else?

**Comment by shaobo-he** [comment] 2020-05-09 19:37
> Could you attach bc file for this?
> Also, I could not find memcmp in the LLVM language reference manual. Are you referring here to the memcmp C standard library function: https://en.cppreference.com/w/c/string/byte/memcmp
> ???
> Or something else?

This is from C standard library.

**Comment by zvonimir** [comment] 2020-05-09 20:01
Oh, I see. But how does then Rust use it? As an external call into C?

**Comment by shaobo-he** [comment] 2020-05-09 20:27
> Oh, I see. But how does then Rust use it? As an external call into C?

I don't know. The function shows up in the LLVM IR file rustc generates.

**Comment by zvonimir** [comment] 2020-10-26 02:17
This is a duplicate of #629. It got closed by this pull request #630.

**Closed by zvonimir** 2020-10-26 02:17 UTC
Labels: duplicate, enhancement
