### ISSUE TITLE
Atomicity of (stack) allocation.

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#525] opened 2019-12-13 21:18 UTC
It seems that when Smack’s `$$alloc` function is not thread safe!

Here’s a program demonstrating the problem:
```console
% cat a.c && smack --pthread --context-bound 2 a.c
#include <smack.h>
#include <pthread.h>
#include <stdlib.h>

struct atomic_var {
    void *value;
};

struct S {
    struct atomic_var x;
    struct atomic_var y;
};

struct T {
    int z;
};

void atomic_store_ptr(struct atomic_var *var, void *p) {
    __atomic_store_n(&var->value, p, __ATOMIC_SEQ_CST);
}

void *foo(void *arg) {
    struct T t = *(struct T *) arg;
    return NULL;
}

int main() {
    struct S s;
    struct T t;
    pthread_t thread;

    (*(size_t *) (s.x.value)) = 0;
    s.y.value = NULL;

    if (pthread_create(&thread, NULL, foo, (void *)&t))
        return 1;

    uint64_t v = (size_t) s.x.value;
    atomic_store_ptr(&s.y, NULL);
    uint64_t w = (size_t) s.x.value;
    assert(v == w);
    return 0;
}
SMACK program verifier version 2.4.0
/usr/local/share/smack/lib/smack.c(45,1): This assertion can fail
Execution trace:
...
```
If we reverify the same Boogie code with an atomic `$$alloc` function, this behaves as expected:
```console
% git diff a.bpl && corral a.bpl /tryCTrace /noTraceOnDisk /printDataValues:1 /k:2 /useProverEvaluate /timeLimit:1200 /cex:1 /maxStaticLoopBound:1 /recursionBound:1 /bopt:proverOpt:OPTIMIZE_FOR_BV=true /bopt:boolControlVC
diff --git a/a.bpl b/a.bpl
index a8f74f8..9c3877b 100644
--- a/a.bpl
+++ b/a.bpl
@@ -1872,6 +1872,7 @@ var $CurrAddr:ref;
 procedure {:inline 1} $$alloc(n: ref) returns (p: ref)
 modifies $CurrAddr;
 {
+  call corral_atomic_begin();
   assume $sge.ref.bool(n, $0.ref);
   if ($sgt.ref.bool(n, $0.ref)) {
     p := $CurrAddr;
@@ -1881,6 +1882,7 @@ modifies $CurrAddr;
   } else {
     p := $0.ref;
   }
+  call corral_atomic_end();
 }
 
 procedure  $free(p: ref);
LB: Took 0.00 s
Verifying program while tracking: {}
Program has a potential bug: False bug
Verifying program while tracking: {$CurrAddr, $M.0}
Program has no bugs
```

**Comment by michael-emmi** [comment] 2019-12-13 21:19
^ @nchong-at-aws

**Comment by michael-emmi** [comment] 2019-12-13 21:20
Also note: we have probably not thought hard enough about the atomicity of Smacks stubs generally, and may want to do a general audit.

**Comment by zvonimir** [comment] 2019-12-16 01:30
I think that `calloc` and `realloc` should be made atomic too. I think others are fine.

An easy solution would be to make them atomic always, no matter whether `--pthreads` gets selected or not. In that case `corral_atomic_begin` and `corral_atomic_end` are just noops. Now, I would hope that invoking such empty noop procedures would have no impact on performance of sequential verification, but I am not totally sure about that (since allocation procedures get invoked a lot).

Thoughts?

**Comment by nchong-at-aws** [comment] 2019-12-16 18:06
@michael-emmi in your example, I think the statement `(*(size_t *) (s.x.value)) = 0;` should be `(*(size_t *) (&s.x.value)) = 0;`

**Comment by nchong-at-aws** [comment] 2019-12-16 18:14
@zvonimir agreed on `calloc` and `realloc`. There is also some bookkeeping in the `#MEMORY_SAFETY` implementations of malloc/free that should be made atomic too, e.g., `allocatedCounter` increments/decrements.

**Comment by zvonimir** [comment] 2019-12-16 20:44
Since I am a tiny bit worried about performance implications, we'll do a run of our SVCOMP benchmarks to make sure this update doesn't break anything major. This will take a few days to run. Sorry about the delay.

**Comment by nchong-at-aws** [comment] 2019-12-17 15:47
Here are three tests (including the one above) that seem related to the atomicity of smack allocation stubs. Currently all three fail with `--pthread --context-bound 2`.

**Comment by zvonimir** [comment] 2020-02-18 20:41
I created a pull request that fixes this issue. Along the way I uncovered a separate issue with the calloc regression - thread id as bv is not quite working. I am working on resolving that one, but it'll be in a separate pull request.

**Comment by zvonimir** [comment] 2020-02-19 23:22
This is now fixed.

**Closed by zvonimir** 2020-02-19 23:22 UTC
Labels: bug

**Comment by nchong-at-aws** [comment] 2020-02-19 23:28
Great! Thanks @zvonimir.
