### ISSUE TITLE
Assertion failure in contract extraction

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#275] opened 2017-10-19 01:42 UTC
This code raises an assertion failure:
````c
#include <smack-contracts.h>

int foo(void);

void bar(void) {
  int x = foo();

  while (x)
    invariant(x);
}
````
Here’s the command line:
````
$ smack -t a.c
SMACK program verifier version 1.9.0
Assertion failed: (clones.count(O.get()) && "Unvisited block."), function projection, file /Users/mje/Code/smack/lib/smack/ExtractContracts.cpp, line 105.
````

**Comment by shaobo-he** [comment] 2020-02-04 22:52
Closed this issue as I cannot reproduce it on SMACK version 2.4.0.

**Closed by shaobo-he** 2020-02-04 22:52 UTC
